server:
    port: 8204
spring:
    #rabbitmq地址
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
    application:
        name: service-msm
    cloud:
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
    redis:
        database: 0
        host: localhost
        lettuce:
            pool:
                max-active: 20
                max-wait: -1
                #最大阻塞等待时间(负数表示没限制)
                max-idle: 5
                min-idle: 0
        port: 6379
        timeout: 1800000

