#端口
server:
    port: 80
spring:
    application:
        name: service-gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            routes:
            -   id: service-hosp
                predicates: Path=/*/hosp/**
                uri: lb://service-hosp
            -   id: service-cmn
                predicates: Path=/*/cmn/**
                uri: lb://service-cmn
            -   id: service-user
                predicates: Path=/*/user/**
                uri: lb://service-user
            -   id: service-msm
                predicates: Path=/*/msm/**
                uri: lb://service-msm
            -   id: service-user
                predicates: Path=/*/ucenter/**
                uri: lb://service-user
            -   id: service-oss
                predicates: Path=/*/oss/**
                uri: lb://service-oss
        nacos:
            discovery:
                server-addr: 127.0.0.1:8848
